### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function mb_internal_encoding()

### ISSUE THREAD

**Issue by 3kami3** [usvn/usvn#83]
I get the following error when performing a signup with LDAP.
```
Fatal error: Uncaught Error: Call to undefined function mb_internal_encoding() in /var/www/usvn/library/Zend/Validate/Hostname.php:517 
Stack trace: 
#0 /var/www/usvn/library/Zend/Validate/EmailAddress.php(487): Zend_Validate_Hostname->isValid() 
#1 /var/www/usvn/library/Zend/Validate/EmailAddress.php(546): Zend_Validate_EmailAddress->_validateHostnamePart() 
#2 /var/www/usvn/library/USVN/Db/Table/Row/User.php(151): Zend_Validate_EmailAddress->isValid() 
#3 /var/www/usvn/library/USVN/Db/Table/Row/User.php(185): USVN_Db_Table_Row_User->checkEmailAddress() 
#4 /var/www/usvn/library/Zend/Db/Table/Row/Abstract.php(475): USVN_Db_Table_Row_User->_insert() 
#5 /var/www/usvn/library/Zend/Db/Table/Row/Abstract.php(452): Zend_Db_Table_Row_Abstract->_doInsert() 
#6 /var/www/usvn/library/USVN/User.php(92): Zend_Db_Table_Row_Abstract->save() 
#7 /var/www/usvn/app/controllers/LoginController.php(146): USVN_User->save() 
#8 /var/www/usvn/app/controllers/LoginController.php(36): LoginController->_doLogin() 
#9 /var/www/usvn/library/Zend/Controller/ in /var/www/usvn/library/Zend/Validate/Hostname.php on line 517
```
* Usvn version: 1.0.11
* PHP version 7.4.33

The following version works.
* Usvn version: 1.0.10
* PHP version 7.4.33

I think it is because of the commit ffa571ad5a5689181ce960fec9a67f185d51bc97 merged in 1.0.11.
Do you know anything about this error? @thewebbooth

**Comment by 3kami3** [comment]
Thanks for the quick advice.
The `extension=mbstring` in php.ini was commented out with a semicolon.

The following steps solved this problem.
```
$ sudo apt-get install php-mbstring
$ sudo sed -i "s/^;extension=mbstring/extension=mbstring/" /etc/php/7.4/apache2/php.ini
```
I see that the mbstring extension is required as a dependent module since 1.0.11.

**Comment by 3kami3** [comment]
Problem solved, I'll close.
